language: node_js
node_js:
  - "18"

cache:
  directories:
    - node_modules
    - ~/.npm

install:
  - npm install

before_script:
  - npm config set progress false
script:
  - yarn test
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
