const dummy_data = [
    [
        {
            "month": 12,
            "year": 2021,
            "type_count": {
                "Berry": 27,
                "Pome Fruit": 10,
                "Stone Fruit": 31,
                "Allium": 31,
                "Cruciferous": 39,
                "Soft Herb": 39,
                "Nightshade": 75,
                "Woody Herb": 13,
                "Vine Fruit": 16,
                "Root": 53,
                "Leaf": 27,
                "False Fruit": 8,
                "Legume": 35,
                "Cucurbit": 27,
                "Citrus": 40,
                "Hard Herb": 29,
                "Flower": 23,
                "Nut": 8,
                "Seed": 9,
                "Stalk": 9
            },
            "supertype_count": {
                "Fruit": 140,
                "Vegetable": 296,
                "Herb": 81,
                "Flower": 32
            },
            "subtype_count": {
                "Blackberry": 7,
                "Apple": 10,
                "Plum": 22,
                "Strawberry": 6,
                "Leek": 7,
                "Broccoli": 6,
                "Basil": 7,
                "Tomato": 47,
                "Oregano": 5,
                "Cabbage": 15,
                "Pepper": 14,
                "Grape": 8,
                "Beetroot": 9,
                "Turnip": 5,
                "Sorrel": 6,
                "Fig": 8,
                "Bean": 31,
                "Squash": 10,
                "Pumpkin": 6,
                "Lime": 7,
                "Thyme": 12,
                "Marjoram": 5,
                "Mint": 10,
                "Nasturtium": 12,
                "Parsley": 12,
                "Cauliflower": 5,
                "Sweet Potato": 9,
                "Chilli": 9,
                "Curry Leaf": 8,
                "Orange": 14,
                "Grapefruit": 10,
                "Cucumber": 6,
                "Gooseberry": 9,
                "Onion": 19,
                "Almond": 8,
                "Artichoke": 9,
                "Peach": 9,
                "Kale": 13,
                "Zucchini": 5,
                "Lettuce": 9,
                "Pea": 4,
                "Sunflower Seed": 9,
                "Kei Apple": 3,
                "Rosemary": 4,
                "Rhubarb": 2,
                "Carrot": 8,
                "Naartjie": 5,
                "Coriander": 5,
                "Turmeric": 6,
                "Spinach": 5,
                "Celery": 7,
                "Sage": 7,
                "Radish": 4,
                "Lemon": 4,
                "Fennel": 3,
                "Blueberry": 2,
                "Mustard Leaf": 7,
                "Chive": 5,
                "Aubergine": 5,
                "Edible Flower": 2,
                "Jerusalem Artichoke": 6,
                "Ginger": 6,
                "Granadilla": 8,
                "Lemon Balm": 2,
                "Lemon Verbena": 1
            }
        },
        {
            "month": 11,
            "year": 2021,
            "type_count": {
                "Legume": 36,
                "Nightshade": 64,
                "Hard Herb": 25,
                "Stone Fruit": 28,
                "Leaf": 21,
                "Berry": 24,
                "Root": 39,
                "Allium": 28,
                "Pome Fruit": 17,
                "Flower": 16,
                "Seed": 4,
                "Citrus": 23,
                "Stalk": 13,
                "Cucurbit": 37,
                "Woody Herb": 11,
                "Soft Herb": 44,
                "Vine Fruit": 19,
                "False Fruit": 10,
                "Cruciferous": 29,
                "Nut": 7
            },
            "supertype_count": {
                "Vegetable": 267,
                "Herb": 80,
                "Fruit": 128,
                "Flower": 20
            },
            "subtype_count": {
                "Bean": 33,
                "Tomato": 37,
                "Rosemary": 6,
                "Plum": 20,
                "Spinach": 7,
                "Blackberry": 5,
                "Radish": 6,
                "Leek": 10,
                "Apple": 17,
                "Beetroot": 4,
                "Onion": 14,
                "Artichoke": 3,
                "Kei Apple": 6,
                "Pepper": 9,
                "Sunflower Seed": 4,
                "Aubergine": 7,
                "Sweet Potato": 11,
                "Lemon": 3,
                "Marjoram": 4,
                "Chive": 4,
                "Rhubarb": 5,
                "Lime": 3,
                "Squash": 13,
                "Oregano": 6,
                "Mint": 5,
                "Basil": 7,
                "Orange": 12,
                "Grape": 16,
                "Fig": 10,
                "Mustard Leaf": 3,
                "Blueberry": 5,
                "Cabbage": 11,
                "Peach": 8,
                "Pea": 3,
                "Sorrel": 5,
                "Coriander": 13,
                "Pumpkin": 10,
                "Granadilla": 3,
                "Chilli": 11,
                "Ginger": 2,
                "Celery": 8,
                "Thyme": 7,
                "Lemon Verbena": 3,
                "Kale": 8,
                "Fennel": 4,
                "Zucchini": 5,
                "Nasturtium": 4,
                "Naartjie": 2,
                "Parsley": 9,
                "Lettuce": 6,
                "Broccoli": 6,
                "Turnip": 4,
                "Strawberry": 6,
                "Turmeric": 5,
                "Sage": 5,
                "Cauliflower": 4,
                "Cucumber": 9,
                "Curry Leaf": 5,
                "Edible Flower": 9,
                "Lemon Balm": 6,
                "Jerusalem Artichoke": 6,
                "Gooseberry": 2,
                "Almond": 7,
                "Carrot": 1,
                "Grapefruit": 3
            }
        },
        {
            "month": 10,
            "year": 2021,
            "type_count": {
                "Vine Fruit": 24,
                "Cruciferous": 33,
                "Woody Herb": 12,
                "Nightshade": 59,
                "Hard Herb": 38,
                "Citrus": 35,
                "Stalk": 16,
                "Legume": 37,
                "Cucurbit": 38,
                "Soft Herb": 37,
                "False Fruit": 7,
                "Flower": 23,
                "Stone Fruit": 36,
                "Leaf": 23,
                "Berry": 29,
                "Root": 55,
                "Pome Fruit": 11,
                "Allium": 24,
                "Seed": 6,
                "Nut": 9
            },
            "supertype_count": {
                "Fruit": 151,
                "Vegetable": 285,
                "Herb": 87,
                "Flower": 29
            },
            "subtype_count": {
                "Granadilla": 9,
                "Grape": 15,
                "Cauliflower": 7,
                "Curry Leaf": 7,
                "Kale": 9,
                "Chilli": 13,
                "Rosemary": 10,
                "Cabbage": 14,
                "Naartjie": 5,
                "Rhubarb": 9,
                "Broccoli": 3,
                "Bean": 31,
                "Pumpkin": 16,
                "Basil": 4,
                "Orange": 13,
                "Fig": 7,
                "Squash": 8,
                "Edible Flower": 8,
                "Celery": 7,
                "Nasturtium": 10,
                "Thyme": 9,
                "Plum": 25,
                "Fennel": 7,
                "Spinach": 7,
                "Strawberry": 8,
                "Lemon Verbena": 6,
                "Jerusalem Artichoke": 9,
                "Tomato": 32,
                "Cucumber": 5,
                "Oregano": 5,
                "Carrot": 8,
                "Peach": 11,
                "Apple": 11,
                "Lemon": 6,
                "Onion": 16,
                "Sunflower Seed": 6,
                "Lemon Balm": 9,
                "Leek": 5,
                "Almond": 9,
                "Artichoke": 5,
                "Parsley": 6,
                "Blackberry": 4,
                "Zucchini": 9,
                "Sweet Potato": 15,
                "Turmeric": 6,
                "Sage": 5,
                "Pea": 6,
                "Radish": 2,
                "Pepper": 10,
                "Marjoram": 8,
                "Gooseberry": 11,
                "Kei Apple": 5,
                "Lettuce": 8,
                "Ginger": 3,
                "Lime": 4,
                "Grapefruit": 7,
                "Coriander": 5,
                "Mint": 6,
                "Turnip": 7,
                "Chive": 3,
                "Aubergine": 4,
                "Sorrel": 4,
                "Beetroot": 5,
                "Mustard Leaf": 4,
                "Blueberry": 1
            }
        },
        {
            "month": 9,
            "year": 2021,
            "type_count": {
                "Cucurbit": 33,
                "Cruciferous": 35,
                "Hard Herb": 19,
                "Vine Fruit": 31,
                "Citrus": 45,
                "Nightshade": 55,
                "Root": 48,
                "Legume": 54,
                "Leaf": 17,
                "Stalk": 12,
                "Soft Herb": 35,
                "False Fruit": 11,
                "Allium": 33,
                "Berry": 32,
                "Woody Herb": 8,
                "Stone Fruit": 25,
                "Flower": 19,
                "Pome Fruit": 8,
                "Seed": 5,
                "Nut": 8
            },
            "supertype_count": {
                "Vegetable": 287,
                "Herb": 62,
                "Fruit": 160,
                "Flower": 24
            },
            "subtype_count": {
                "Squash": 16,
                "Kale": 5,
                "Thyme": 6,
                "Grape": 21,
                "Grapefruit": 9,
                "Tomato": 28,
                "Orange": 12,
                "Cucumber": 2,
                "Sweet Potato": 14,
                "Bean": 47,
                "Zucchini": 3,
                "Pepper": 11,
                "Spinach": 3,
                "Lettuce": 7,
                "Cabbage": 16,
                "Celery": 5,
                "Fennel": 8,
                "Beetroot": 6,
                "Broccoli": 6,
                "Aubergine": 8,
                "Fig": 11,
                "Mint": 7,
                "Onion": 23,
                "Leek": 6,
                "Gooseberry": 12,
                "Parsley": 8,
                "Rosemary": 4,
                "Pumpkin": 12,
                "Curry Leaf": 7,
                "Sorrel": 4,
                "Peach": 7,
                "Blackberry": 10,
                "Chilli": 8,
                "Plum": 18,
                "Pea": 7,
                "Radish": 3,
                "Carrot": 3,
                "Marjoram": 2,
                "Rhubarb": 7,
                "Jerusalem Artichoke": 6,
                "Edible Flower": 7,
                "Cauliflower": 8,
                "Sage": 2,
                "Kei Apple": 2,
                "Apple": 8,
                "Lemon": 11,
                "Granadilla": 10,
                "Lemon Balm": 5,
                "Naartjie": 8,
                "Mustard Leaf": 3,
                "Nasturtium": 7,
                "Sunflower Seed": 5,
                "Basil": 4,
                "Lemon Verbena": 5,
                "Artichoke": 5,
                "Strawberry": 4,
                "Lime": 5,
                "Ginger": 7,
                "Turmeric": 4,
                "Turnip": 5,
                "Almond": 8,
                "Blueberry": 4,
                "Coriander": 3,
                "Oregano": 1,
                "Chive": 4
            }
        },
        {
            "month": 8,
            "year": 2021,
            "type_count": {
                "Berry": 26,
                "Allium": 27,
                "Nightshade": 43,
                "Vine Fruit": 21,
                "Root": 47,
                "Soft Herb": 28,
                "Legume": 39,
                "Citrus": 43,
                "Hard Herb": 25,
                "Cucurbit": 42,
                "Flower": 15,
                "Woody Herb": 12,
                "False Fruit": 13,
                "Stone Fruit": 36,
                "Pome Fruit": 13,
                "Stalk": 16,
                "Nut": 6,
                "Cruciferous": 25,
                "Seed": 8,
                "Leaf": 18
            },
            "supertype_count": {
                "Fruit": 158,
                "Vegetable": 257,
                "Herb": 65,
                "Flower": 23
            },
            "subtype_count": {
                "Kei Apple": 6,
                "Onion": 12,
                "Aubergine": 10,
                "Pepper": 5,
                "Grape": 19,
                "Beetroot": 7,
                "Leek": 8,
                "Sweet Potato": 10,
                "Coriander": 4,
                "Bean": 37,
                "Blueberry": 5,
                "Orange": 11,
                "Lemon": 9,
                "Sage": 2,
                "Pumpkin": 16,
                "Edible Flower": 5,
                "Curry Leaf": 4,
                "Fig": 13,
                "Thyme": 7,
                "Tomato": 26,
                "Gooseberry": 6,
                "Peach": 17,
                "Parsley": 9,
                "Apple": 13,
                "Celery": 6,
                "Almond": 6,
                "Chilli": 2,
                "Cucumber": 5,
                "Plum": 19,
                "Kale": 8,
                "Oregano": 8,
                "Lemon Verbena": 3,
                "Grapefruit": 13,
                "Blackberry": 6,
                "Basil": 2,
                "Marjoram": 6,
                "Naartjie": 7,
                "Squash": 16,
                "Zucchini": 5,
                "Cabbage": 13,
                "Mint": 8,
                "Carrot": 8,
                "Ginger": 4,
                "Chive": 7,
                "Sunflower Seed": 8,
                "Rhubarb": 10,
                "Turnip": 9,
                "Lemon Balm": 4,
                "Lettuce": 7,
                "Mustard Leaf": 3,
                "Rosemary": 7,
                "Radish": 4,
                "Nasturtium": 3,
                "Sorrel": 7,
                "Jerusalem Artichoke": 3,
                "Artichoke": 7,
                "Lime": 3,
                "Spinach": 1,
                "Fennel": 1,
                "Broccoli": 4,
                "Strawberry": 3,
                "Granadilla": 2,
                "Pea": 2,
                "Turmeric": 2
            }
        },
        {
            "month": 7,
            "year": 2021,
            "type_count": {
                "Cucurbit": 33,
                "Nightshade": 54,
                "Stone Fruit": 40,
                "Cruciferous": 28,
                "Pome Fruit": 9,
                "Legume": 44,
                "Berry": 32,
                "Citrus": 32,
                "Root": 53,
                "False Fruit": 3,
                "Stalk": 15,
                "Vine Fruit": 15,
                "Flower": 24,
                "Seed": 6,
                "Leaf": 22,
                "Soft Herb": 31,
                "Allium": 27,
                "Hard Herb": 18,
                "Nut": 5,
                "Woody Herb": 8
            },
            "supertype_count": {
                "Vegetable": 276,
                "Fruit": 136,
                "Flower": 30,
                "Herb": 57
            },
            "subtype_count": {
                "Cucumber": 5,
                "Tomato": 24,
                "Plum": 27,
                "Pepper": 15,
                "Broccoli": 3,
                "Apple": 9,
                "Bean": 41,
                "Gooseberry": 10,
                "Grapefruit": 3,
                "Turmeric": 6,
                "Peach": 13,
                "Fig": 3,
                "Celery": 6,
                "Naartjie": 7,
                "Grape": 13,
                "Edible Flower": 10,
                "Sunflower Seed": 6,
                "Artichoke": 6,
                "Sorrel": 7,
                "Orange": 11,
                "Rhubarb": 9,
                "Lemon": 8,
                "Coriander": 5,
                "Cabbage": 14,
                "Kale": 6,
                "Blackberry": 8,
                "Jerusalem Artichoke": 5,
                "Sweet Potato": 11,
                "Squash": 12,
                "Basil": 6,
                "Nasturtium": 8,
                "Beetroot": 8,
                "Turnip": 4,
                "Chilli": 9,
                "Granadilla": 2,
                "Kei Apple": 3,
                "Pumpkin": 13,
                "Mint": 7,
                "Leek": 8,
                "Strawberry": 6,
                "Thyme": 4,
                "Lemon Balm": 9,
                "Mustard Leaf": 7,
                "Rosemary": 2,
                "Lime": 3,
                "Aubergine": 6,
                "Zucchini": 3,
                "Onion": 17,
                "Blueberry": 5,
                "Cauliflower": 5,
                "Fennel": 3,
                "Spinach": 4,
                "Almond": 5,
                "Curry Leaf": 5,
                "Pea": 3,
                "Radish": 5,
                "Oregano": 3,
                "Carrot": 7,
                "Marjoram": 7,
                "Ginger": 7,
                "Lettuce": 4,
                "Lemon Verbena": 3,
                "Parsley": 1,
                "Sage": 2,
                "Chive": 2
            }
        },
        {
            "month": 6,
            "year": 2021,
            "type_count": {
                "Cucurbit": 22,
                "Legume": 42,
                "Citrus": 40,
                "Leaf": 18,
                "Hard Herb": 43,
                "Soft Herb": 36,
                "Nightshade": 56,
                "Flower": 20,
                "Root": 50,
                "Vine Fruit": 21,
                "Allium": 38,
                "Pome Fruit": 13,
                "Woody Herb": 14,
                "Stalk": 13,
                "Berry": 32,
                "False Fruit": 9,
                "Seed": 6,
                "Cruciferous": 32,
                "Stone Fruit": 38,
                "Nut": 5
            },
            "supertype_count": {
                "Vegetable": 271,
                "Fruit": 158,
                "Herb": 93,
                "Flower": 26
            },
            "subtype_count": {
                "Cucumber": 4,
                "Pea": 6,
                "Orange": 11,
                "Lettuce": 5,
                "Lemon Verbena": 12,
                "Marjoram": 9,
                "Mint": 7,
                "Bean": 36,
                "Chilli": 8,
                "Artichoke": 5,
                "Ginger": 4,
                "Grape": 15,
                "Onion": 26,
                "Jerusalem Artichoke": 4,
                "Rosemary": 7,
                "Apple": 13,
                "Curry Leaf": 9,
                "Celery": 10,
                "Turmeric": 11,
                "Kei Apple": 8,
                "Fig": 9,
                "Sorrel": 4,
                "Turnip": 5,
                "Pepper": 11,
                "Tomato": 32,
                "Beetroot": 5,
                "Sunflower Seed": 6,
                "Lemon": 5,
                "Cabbage": 11,
                "Broccoli": 7,
                "Blackberry": 5,
                "Parsley": 5,
                "Plum": 24,
                "Granadilla": 6,
                "Basil": 6,
                "Pumpkin": 6,
                "Mustard Leaf": 7,
                "Peach": 14,
                "Nasturtium": 7,
                "Gooseberry": 12,
                "Sweet Potato": 7,
                "Almond": 5,
                "Lime": 11,
                "Sage": 7,
                "Oregano": 5,
                "Radish": 6,
                "Edible Flower": 8,
                "Coriander": 8,
                "Thyme": 8,
                "Kale": 7,
                "Naartjie": 9,
                "Leek": 5,
                "Lemon Balm": 3,
                "Blueberry": 4,
                "Cauliflower": 7,
                "Carrot": 8,
                "Chive": 7,
                "Aubergine": 5,
                "Squash": 9,
                "Rhubarb": 3,
                "Zucchini": 3,
                "Grapefruit": 4,
                "Fennel": 7,
                "Spinach": 2,
                "Strawberry": 3
            }
        },
        {
            "month": 5,
            "year": 2021,
            "type_count": {
                "Hard Herb": 31,
                "Soft Herb": 35,
                "Cucurbit": 39,
                "Legume": 45,
                "Allium": 30,
                "Cruciferous": 32,
                "Nightshade": 64,
                "Vine Fruit": 24,
                "Pome Fruit": 11,
                "Stone Fruit": 37,
                "Citrus": 36,
                "Stalk": 13,
                "Flower": 16,
                "Root": 34,
                "Berry": 29,
                "Leaf": 18,
                "False Fruit": 10,
                "Woody Herb": 11,
                "Nut": 6,
                "Seed": 2
            },
            "supertype_count": {
                "Herb": 77,
                "Vegetable": 275,
                "Fruit": 153,
                "Flower": 18
            },
            "subtype_count": {
                "Rosemary": 10,
                "Fennel": 4,
                "Squash": 15,
                "Bean": 38,
                "Onion": 19,
                "Cauliflower": 6,
                "Thyme": 7,
                "Tomato": 28,
                "Pumpkin": 14,
                "Grape": 16,
                "Apple": 11,
                "Coriander": 5,
                "Parsley": 8,
                "Plum": 20,
                "Lime": 11,
                "Celery": 7,
                "Basil": 7,
                "Pepper": 14,
                "Cabbage": 9,
                "Peach": 17,
                "Nasturtium": 8,
                "Orange": 11,
                "Lemon Verbena": 5,
                "Carrot": 5,
                "Pea": 7,
                "Artichoke": 6,
                "Kale": 12,
                "Naartjie": 6,
                "Beetroot": 3,
                "Blueberry": 10,
                "Sorrel": 6,
                "Fig": 10,
                "Lemon Balm": 5,
                "Chilli": 19,
                "Spinach": 5,
                "Lemon": 4,
                "Zucchini": 5,
                "Cucumber": 5,
                "Mustard Leaf": 3,
                "Grapefruit": 4,
                "Sage": 5,
                "Sweet Potato": 13,
                "Mint": 6,
                "Chive": 5,
                "Rhubarb": 6,
                "Ginger": 6,
                "Blackberry": 8,
                "Broccoli": 5,
                "Lettuce": 4,
                "Curry Leaf": 3,
                "Almond": 6,
                "Aubergine": 3,
                "Kei Apple": 2,
                "Marjoram": 4,
                "Oregano": 8,
                "Granadilla": 8,
                "Leek": 6,
                "Radish": 3,
                "Strawberry": 6,
                "Edible Flower": 2,
                "Turmeric": 3,
                "Jerusalem Artichoke": 1,
                "Gooseberry": 3,
                "Sunflower Seed": 2
            }
        },
        {
            "month": 4,
            "year": 2021,
            "type_count": {
                "Nightshade": 69,
                "Soft Herb": 35,
                "Legume": 51,
                "Hard Herb": 30,
                "Root": 44,
                "Cruciferous": 28,
                "Citrus": 32,
                "Stalk": 17,
                "False Fruit": 15,
                "Cucurbit": 38,
                "Seed": 9,
                "Flower": 18,
                "Allium": 22,
                "Nut": 6,
                "Berry": 23,
                "Stone Fruit": 44,
                "Vine Fruit": 22,
                "Leaf": 19,
                "Pome Fruit": 9,
                "Woody Herb": 11
            },
            "supertype_count": {
                "Vegetable": 288,
                "Herb": 76,
                "Fruit": 151,
                "Flower": 27
            },
            "subtype_count": {
                "Tomato": 41,
                "Mint": 4,
                "Bean": 48,
                "Sage": 6,
                "Sweet Potato": 12,
                "Kale": 7,
                "Lemon": 6,
                "Rhubarb": 8,
                "Fig": 15,
                "Orange": 12,
                "Pumpkin": 10,
                "Chilli": 11,
                "Sunflower Seed": 9,
                "Naartjie": 6,
                "Beetroot": 4,
                "Turnip": 10,
                "Celery": 9,
                "Lemon Verbena": 9,
                "Thyme": 7,
                "Fennel": 8,
                "Nasturtium": 4,
                "Onion": 15,
                "Broccoli": 5,
                "Zucchini": 10,
                "Cucumber": 6,
                "Almond": 6,
                "Aubergine": 4,
                "Kei Apple": 5,
                "Plum": 31,
                "Coriander": 8,
                "Granadilla": 6,
                "Cauliflower": 4,
                "Lettuce": 7,
                "Peach": 13,
                "Lemon Balm": 7,
                "Artichoke": 4,
                "Grape": 16,
                "Basil": 5,
                "Cabbage": 12,
                "Jerusalem Artichoke": 4,
                "Blueberry": 4,
                "Gooseberry": 4,
                "Edible Flower": 10,
                "Leek": 3,
                "Turmeric": 4,
                "Chive": 4,
                "Squash": 12,
                "Pepper": 13,
                "Marjoram": 7,
                "Spinach": 5,
                "Apple": 9,
                "Lime": 5,
                "Curry Leaf": 4,
                "Oregano": 7,
                "Ginger": 4,
                "Rosemary": 1,
                "Pea": 3,
                "Blackberry": 3,
                "Strawberry": 7,
                "Grapefruit": 3,
                "Sorrel": 6,
                "Radish": 3,
                "Parsley": 3,
                "Carrot": 3,
                "Mustard Leaf": 1
            }
        },
        {
            "month": 3,
            "year": 2021,
            "type_count": {
                "Legume": 42,
                "False Fruit": 12,
                "Vine Fruit": 24,
                "Nightshade": 61,
                "Soft Herb": 31,
                "Root": 61,
                "Berry": 33,
                "Citrus": 32,
                "Hard Herb": 27,
                "Stone Fruit": 41,
                "Stalk": 8,
                "Allium": 26,
                "Cruciferous": 34,
                "Cucurbit": 23,
                "Nut": 6,
                "Flower": 18,
                "Woody Herb": 8,
                "Seed": 6,
                "Pome Fruit": 13,
                "Leaf": 23
            },
            "supertype_count": {
                "Vegetable": 278,
                "Fruit": 161,
                "Herb": 66,
                "Flower": 24
            },
            "subtype_count": {
                "Bean": 38,
                "Fig": 12,
                "Grape": 16,
                "Chilli": 11,
                "Parsley": 10,
                "Jerusalem Artichoke": 7,
                "Blueberry": 6,
                "Lemon": 4,
                "Thyme": 9,
                "Plum": 31,
                "Tomato": 33,
                "Rhubarb": 4,
                "Chive": 4,
                "Kale": 15,
                "Cauliflower": 3,
                "Kei Apple": 7,
                "Sweet Potato": 16,
                "Pumpkin": 8,
                "Almond": 6,
                "Broccoli": 6,
                "Peach": 10,
                "Blackberry": 6,
                "Onion": 19,
                "Ginger": 6,
                "Orange": 12,
                "Pepper": 13,
                "Granadilla": 8,
                "Sage": 7,
                "Nasturtium": 6,
                "Squash": 5,
                "Oregano": 5,
                "Pea": 4,
                "Marjoram": 1,
                "Cucumber": 8,
                "Sunflower Seed": 6,
                "Naartjie": 3,
                "Apple": 13,
                "Lime": 8,
                "Carrot": 9,
                "Lemon Verbena": 6,
                "Turnip": 9,
                "Radish": 7,
                "Mustard Leaf": 11,
                "Rosemary": 4,
                "Aubergine": 4,
                "Strawberry": 10,
                "Basil": 5,
                "Beetroot": 4,
                "Sorrel": 6,
                "Artichoke": 6,
                "Edible Flower": 6,
                "Cabbage": 10,
                "Celery": 4,
                "Turmeric": 3,
                "Mint": 5,
                "Lettuce": 3,
                "Zucchini": 2,
                "Gooseberry": 4,
                "Grapefruit": 5,
                "Curry Leaf": 3,
                "Coriander": 6,
                "Spinach": 3,
                "Leek": 3,
                "Fennel": 2,
                "Lemon Balm": 3
            }
        },
        {
            "month": 2,
            "year": 2021,
            "type_count": {
                "Leaf": 16,
                "Root": 56,
                "Seed": 6,
                "Woody Herb": 9,
                "Nightshade": 62,
                "Stalk": 15,
                "False Fruit": 15,
                "Cruciferous": 22,
                "Stone Fruit": 34,
                "Legume": 42,
                "Berry": 39,
                "Vine Fruit": 29,
                "Cucurbit": 34,
                "Soft Herb": 25,
                "Hard Herb": 22,
                "Pome Fruit": 10,
                "Allium": 27,
                "Citrus": 25,
                "Nut": 11,
                "Flower": 11
            },
            "supertype_count": {
                "Vegetable": 274,
                "Flower": 17,
                "Herb": 56,
                "Fruit": 163
            },
            "subtype_count": {
                "Sorrel": 6,
                "Turmeric": 6,
                "Sunflower Seed": 6,
                "Curry Leaf": 6,
                "Chilli": 13,
                "Celery": 7,
                "Fig": 15,
                "Cabbage": 4,
                "Plum": 25,
                "Bean": 36,
                "Strawberry": 8,
                "Grape": 22,
                "Cauliflower": 5,
                "Spinach": 4,
                "Granadilla": 7,
                "Tomato": 31,
                "Jerusalem Artichoke": 6,
                "Ginger": 10,
                "Squash": 9,
                "Peach": 9,
                "Fennel": 3,
                "Lettuce": 4,
                "Thyme": 7,
                "Blackberry": 9,
                "Pepper": 12,
                "Apple": 10,
                "Onion": 16,
                "Lemon": 6,
                "Rosemary": 3,
                "Turnip": 10,
                "Zucchini": 9,
                "Broccoli": 3,
                "Blueberry": 11,
                "Mustard Leaf": 2,
                "Almond": 11,
                "Basil": 6,
                "Pumpkin": 10,
                "Kale": 10,
                "Chive": 7,
                "Marjoram": 3,
                "Lime": 5,
                "Beetroot": 7,
                "Cucumber": 6,
                "Coriander": 3,
                "Oregano": 3,
                "Nasturtium": 4,
                "Naartjie": 2,
                "Leek": 4,
                "Orange": 12,
                "Parsley": 4,
                "Kei Apple": 5,
                "Pea": 6,
                "Edible Flower": 4,
                "Artichoke": 3,
                "Lemon Verbena": 7,
                "Rhubarb": 8,
                "Mint": 6,
                "Lemon Balm": 3,
                "Carrot": 5,
                "Radish": 7,
                "Aubergine": 6,
                "Sage": 2,
                "Gooseberry": 6,
                "Sweet Potato": 5
            }
        },
        {
            "month": 1,
            "year": 2021,
            "type_count": {
                "Nightshade": 57,
                "Citrus": 32,
                "Vine Fruit": 29,
                "Cruciferous": 38,
                "Pome Fruit": 11,
                "Cucurbit": 27,
                "Root": 62,
                "Hard Herb": 31,
                "Flower": 23,
                "Soft Herb": 41,
                "Leaf": 20,
                "Berry": 28,
                "Seed": 8,
                "Nut": 8,
                "Legume": 26,
                "Stone Fruit": 36,
                "Stalk": 15,
                "Woody Herb": 8,
                "Allium": 22,
                "False Fruit": 9
            },
            "supertype_count": {
                "Vegetable": 267,
                "Fruit": 153,
                "Herb": 80,
                "Flower": 31
            },
            "subtype_count": {
                "Tomato": 27,
                "Orange": 13,
                "Grape": 23,
                "Cabbage": 15,
                "Pepper": 11,
                "Chilli": 13,
                "Apple": 11,
                "Squash": 6,
                "Carrot": 9,
                "Rosemary": 7,
                "Ginger": 11,
                "Artichoke": 10,
                "Pumpkin": 13,
                "Naartjie": 6,
                "Basil": 10,
                "Spinach": 5,
                "Kei Apple": 5,
                "Fennel": 8,
                "Cauliflower": 9,
                "Sunflower Seed": 8,
                "Radish": 5,
                "Mint": 5,
                "Edible Flower": 6,
                "Marjoram": 9,
                "Almond": 8,
                "Turnip": 7,
                "Bean": 25,
                "Blueberry": 9,
                "Sage": 4,
                "Zucchini": 3,
                "Peach": 15,
                "Celery": 4,
                "Sweet Potato": 10,
                "Lemon Balm": 7,
                "Jerusalem Artichoke": 5,
                "Granadilla": 6,
                "Plum": 21,
                "Broccoli": 7,
                "Curry Leaf": 2,
                "Lemon": 7,
                "Blackberry": 6,
                "Lime": 3,
                "Kale": 7,
                "Chive": 7,
                "Rhubarb": 11,
                "Strawberry": 6,
                "Cucumber": 5,
                "Nasturtium": 7,
                "Coriander": 8,
                "Lemon Verbena": 4,
                "Grapefruit": 3,
                "Beetroot": 6,
                "Parsley": 3,
                "Fig": 9,
                "Onion": 12,
                "Pea": 1,
                "Thyme": 7,
                "Sorrel": 7,
                "Lettuce": 4,
                "Oregano": 6,
                "Turmeric": 9,
                "Mustard Leaf": 4,
                "Aubergine": 6,
                "Gooseberry": 2,
                "Leek": 3
            }
        },
        {
            "month": 12,
            "year": 2020,
            "type_count": {
                "Nightshade": 73,
                "Stone Fruit": 47,
                "Root": 49,
                "Woody Herb": 6,
                "Vine Fruit": 21,
                "Soft Herb": 32,
                "Leaf": 30,
                "Cucurbit": 31,
                "Citrus": 39,
                "Berry": 27,
                "Allium": 24,
                "Flower": 16,
                "Legume": 45,
                "Hard Herb": 23,
                "Cruciferous": 30,
                "False Fruit": 14,
                "Pome Fruit": 11,
                "Nut": 8,
                "Stalk": 13,
                "Seed": 1
            },
            "supertype_count": {
                "Vegetable": 295,
                "Fruit": 167,
                "Herb": 61,
                "Flower": 17
            },
            "subtype_count": {
                "Tomato": 40,
                "Plum": 30,
                "Jerusalem Artichoke": 4,
                "Curry Leaf": 4,
                "Granadilla": 5,
                "Carrot": 8,
                "Mint": 4,
                "Spinach": 13,
                "Squash": 11,
                "Orange": 11,
                "Radish": 6,
                "Kei Apple": 5,
                "Onion": 16,
                "Pumpkin": 10,
                "Peach": 17,
                "Artichoke": 4,
                "Gooseberry": 7,
                "Turmeric": 5,
                "Bean": 38,
                "Grape": 16,
                "Cucumber": 8,
                "Sage": 9,
                "Lemon Balm": 11,
                "Cabbage": 8,
                "Sweet Potato": 13,
                "Grapefruit": 6,
                "Parsley": 6,
                "Sorrel": 8,
                "Marjoram": 6,
                "Coriander": 2,
                "Nasturtium": 7,
                "Chive": 5,
                "Lemon Verbena": 4,
                "Fig": 14,
                "Pepper": 12,
                "Naartjie": 10,
                "Turnip": 6,
                "Chilli": 16,
                "Apple": 11,
                "Thyme": 2,
                "Cauliflower": 7,
                "Lemon": 7,
                "Oregano": 2,
                "Rosemary": 2,
                "Blackberry": 4,
                "Almond": 8,
                "Lime": 5,
                "Zucchini": 2,
                "Aubergine": 5,
                "Broccoli": 3,
                "Leek": 3,
                "Strawberry": 4,
                "Edible Flower": 5,
                "Pea": 7,
                "Fennel": 5,
                "Basil": 4,
                "Mustard Leaf": 5,
                "Celery": 4,
                "Ginger": 4,
                "Beetroot": 3,
                "Rhubarb": 9,
                "Kale": 12,
                "Blueberry": 7,
                "Sunflower Seed": 1,
                "Lettuce": 4
            }
        },
        {
            "month": 11,
            "year": 2020,
            "type_count": {
                "Cruciferous": 35,
                "Allium": 31,
                "Stone Fruit": 28,
                "Soft Herb": 45,
                "Pome Fruit": 11,
                "Root": 51,
                "Nightshade": 54,
                "Berry": 33,
                "Legume": 38,
                "Flower": 26,
                "False Fruit": 10,
                "Citrus": 22,
                "Vine Fruit": 25,
                "Leaf": 12,
                "Hard Herb": 25,
                "Cucurbit": 29,
                "Nut": 8,
                "Woody Herb": 10,
                "Stalk": 12,
                "Seed": 4
            },
            "supertype_count": {
                "Vegetable": 262,
                "Fruit": 137,
                "Herb": 80,
                "Flower": 30
            },
            "subtype_count": {
                "Kale": 13,
                "Leek": 9,
                "Plum": 13,
                "Basil": 6,
                "Apple": 11,
                "Carrot": 3,
                "Chilli": 11,
                "Blackberry": 4,
                "Onion": 18,
                "Pea": 6,
                "Nasturtium": 7,
                "Coriander": 3,
                "Blueberry": 9,
                "Cabbage": 13,
                "Tomato": 26,
                "Bean": 32,
                "Fig": 10,
                "Sweet Potato": 9,
                "Lemon": 3,
                "Grape": 18,
                "Cauliflower": 3,
                "Artichoke": 7,
                "Lettuce": 2,
                "Fennel": 13,
                "Lemon Verbena": 6,
                "Zucchini": 3,
                "Sage": 5,
                "Squash": 9,
                "Almond": 8,
                "Ginger": 7,
                "Jerusalem Artichoke": 6,
                "Sorrel": 4,
                "Peach": 15,
                "Beetroot": 10,
                "Curry Leaf": 8,
                "Rhubarb": 8,
                "Strawberry": 10,
                "Pepper": 14,
                "Gooseberry": 3,
                "Parsley": 11,
                "Turnip": 7,
                "Edible Flower": 12,
                "Radish": 6,
                "Mint": 10,
                "Cucumber": 7,
                "Turmeric": 3,
                "Broccoli": 6,
                "Pumpkin": 10,
                "Chive": 4,
                "Mustard Leaf": 3,
                "Celery": 4,
                "Thyme": 3,
                "Kei Apple": 7,
                "Rosemary": 6,
                "Naartjie": 4,
                "Marjoram": 5,
                "Aubergine": 3,
                "Granadilla": 7,
                "Oregano": 2,
                "Lime": 2,
                "Orange": 10,
                "Grapefruit": 3,
                "Spinach": 3,
                "Lemon Balm": 2,
                "Sunflower Seed": 4
            }
        },
        {
            "month": 10,
            "year": 2020,
            "type_count": {
                "Nightshade": 69,
                "Citrus": 36,
                "Leaf": 27,
                "Cucurbit": 23,
                "Berry": 36,
                "Vine Fruit": 22,
                "Soft Herb": 34,
                "Root": 53,
                "Legume": 44,
                "Woody Herb": 7,
                "Allium": 22,
                "Cruciferous": 32,
                "Nut": 6,
                "Hard Herb": 24,
                "Stone Fruit": 38,
                "Seed": 4,
                "Stalk": 13,
                "Pome Fruit": 15,
                "Flower": 16,
                "False Fruit": 8
            },
            "supertype_count": {
                "Vegetable": 283,
                "Fruit": 161,
                "Herb": 65,
                "Flower": 20
            },
            "subtype_count": {
                "Chilli": 13,
                "Lemon": 9,
                "Spinach": 6,
                "Pepper": 13,
                "Pumpkin": 11,
                "Strawberry": 7,
                "Granadilla": 4,
                "Fennel": 5,
                "Radish": 8,
                "Blackberry": 9,
                "Lemon Balm": 6,
                "Bean": 37,
                "Oregano": 3,
                "Orange": 12,
                "Chive": 3,
                "Grape": 18,
                "Basil": 5,
                "Cabbage": 12,
                "Tomato": 36,
                "Parsley": 6,
                "Kale": 11,
                "Almond": 6,
                "Marjoram": 5,
                "Plum": 21,
                "Sunflower Seed": 4,
                "Squash": 4,
                "Kei Apple": 8,
                "Rhubarb": 6,
                "Zucchini": 4,
                "Sorrel": 7,
                "Sage": 5,
                "Grapefruit": 7,
                "Beetroot": 6,
                "Peach": 17,
                "Apple": 15,
                "Curry Leaf": 4,
                "Carrot": 8,
                "Edible Flower": 8,
                "Coriander": 6,
                "Gooseberry": 4,
                "Lettuce": 9,
                "Turmeric": 8,
                "Thyme": 7,
                "Onion": 16,
                "Mustard Leaf": 5,
                "Fig": 8,
                "Celery": 7,
                "Lime": 7,
                "Pea": 7,
                "Rosemary": 5,
                "Artichoke": 4,
                "Leek": 3,
                "Broccoli": 4,
                "Ginger": 4,
                "Blueberry": 8,
                "Jerusalem Artichoke": 6,
                "Cauliflower": 5,
                "Aubergine": 7,
                "Sweet Potato": 11,
                "Mint": 6,
                "Turnip": 2,
                "Cucumber": 4,
                "Nasturtium": 4,
                "Lemon Verbena": 2,
                "Naartjie": 1
            }
        },
        {
            "month": 9,
            "year": 2020,
            "type_count": {
                "Stone Fruit": 29,
                "False Fruit": 17,
                "Nightshade": 70,
                "Leaf": 19,
                "Cucurbit": 35,
                "Citrus": 31,
                "Root": 62,
                "Woody Herb": 7,
                "Berry": 27,
                "Cruciferous": 30,
                "Legume": 43,
                "Allium": 37,
                "Hard Herb": 39,
                "Soft Herb": 24,
                "Pome Fruit": 16,
                "Stalk": 10,
                "Vine Fruit": 22,
                "Flower": 18,
                "Nut": 3,
                "Seed": 7
            },
            "supertype_count": {
                "Fruit": 145,
                "Vegetable": 306,
                "Herb": 70,
                "Flower": 25
            },
            "subtype_count": {
                "Plum": 21,
                "Fig": 17,
                "Tomato": 39,
                "Lettuce": 8,
                "Pumpkin": 17,
                "Pepper": 12,
                "Lime": 3,
                "Sweet Potato": 15,
                "Cucumber": 1,
                "Curry Leaf": 4,
                "Blueberry": 11,
                "Kale": 10,
                "Bean": 34,
                "Beetroot": 5,
                "Grapefruit": 3,
                "Naartjie": 6,
                "Onion": 27,
                "Squash": 14,
                "Lemon Verbena": 7,
                "Orange": 12,
                "Lemon": 7,
                "Chive": 7,
                "Rosemary": 14,
                "Basil": 6,
                "Cauliflower": 6,
                "Jerusalem Artichoke": 7,
                "Turmeric": 7,
                "Apple": 16,
                "Turnip": 8,
                "Rhubarb": 5,
                "Cabbage": 9,
                "Granadilla": 5,
                "Fennel": 6,
                "Thyme": 9,
                "Mustard Leaf": 5,
                "Chilli": 11,
                "Grape": 17,
                "Carrot": 8,
                "Ginger": 5,
                "Edible Flower": 7,
                "Pea": 9,
                "Sage": 7,
                "Mint": 4,
                "Broccoli": 5,
                "Zucchini": 3,
                "Nasturtium": 6,
                "Almond": 3,
                "Strawberry": 5,
                "Celery": 5,
                "Peach": 8,
                "Leek": 3,
                "Gooseberry": 5,
                "Radish": 7,
                "Coriander": 3,
                "Spinach": 3,
                "Aubergine": 8,
                "Sorrel": 3,
                "Sunflower Seed": 7,
                "Oregano": 3,
                "Kei Apple": 2,
                "Blackberry": 4,
                "Marjoram": 2,
                "Artichoke": 5,
                "Lemon Balm": 3,
                "Parsley": 2
            }
        },
        {
            "month": 8,
            "year": 2020,
            "type_count": {
                "Citrus": 38,
                "Stone Fruit": 31,
                "Soft Herb": 48,
                "Woody Herb": 11,
                "Leaf": 20,
                "Cucurbit": 37,
                "Nightshade": 65,
                "Cruciferous": 29,
                "Flower": 14,
                "Root": 47,
                "Vine Fruit": 20,
                "Allium": 24,
                "Stalk": 12,
                "Berry": 23,
                "Legume": 36,
                "False Fruit": 7,
                "Hard Herb": 37,
                "Pome Fruit": 13,
                "Nut": 4,
                "Seed": 4
            },
            "supertype_count": {
                "Fruit": 136,
                "Herb": 96,
                "Vegetable": 270,
                "Flower": 18
            },
            "subtype_count": {
                "Grapefruit": 8,
                "Plum": 21,
                "Mint": 10,
                "Curry Leaf": 7,
                "Sorrel": 4,
                "Cucumber": 6,
                "Chilli": 6,
                "Kale": 12,
                "Naartjie": 5,
                "Nasturtium": 5,
                "Sweet Potato": 11,
                "Grape": 19,
                "Chive": 3,
                "Rhubarb": 7,
                "Blueberry": 3,
                "Tomato": 44,
                "Zucchini": 7,
                "Bean": 34,
                "Fig": 7,
                "Lemon Verbena": 14,
                "Cauliflower": 3,
                "Onion": 17,
                "Spinach": 4,
                "Lemon Balm": 6,
                "Sage": 7,
                "Celery": 5,
                "Pepper": 13,
                "Rosemary": 8,
                "Orange": 16,
                "Fennel": 10,
                "Edible Flower": 4,
                "Gooseberry": 5,
                "Parsley": 11,
                "Turmeric": 3,
                "Peach": 10,
                "Apple": 13,
                "Almond": 4,
                "Mustard Leaf": 9,
                "Kei Apple": 2,
                "Broccoli": 6,
                "Squash": 15,
                "Marjoram": 3,
                "Strawberry": 6,
                "Pea": 2,
                "Artichoke": 5,
                "Cabbage": 8,
                "Basil": 2,
                "Blackberry": 7,
                "Leek": 4,
                "Coriander": 9,
                "Lemon": 5,
                "Lime": 4,
                "Pumpkin": 9,
                "Turnip": 5,
                "Radish": 5,
                "Jerusalem Artichoke": 4,
                "Oregano": 4,
                "Ginger": 7,
                "Carrot": 7,
                "Lettuce": 3,
                "Thyme": 5,
                "Beetroot": 5,
                "Sunflower Seed": 4,
                "Granadilla": 1,
                "Aubergine": 2
            }
        },
        {
            "month": 7,
            "year": 2020,
            "type_count": {
                "Root": 59,
                "Flower": 21,
                "Hard Herb": 34,
                "Leaf": 20,
                "Nightshade": 58,
                "False Fruit": 10,
                "Citrus": 33,
                "Cucurbit": 31,
                "Nut": 10,
                "Legume": 53,
                "Cruciferous": 35,
                "Allium": 27,
                "Soft Herb": 35,
                "Vine Fruit": 18,
                "Stone Fruit": 27,
                "Seed": 7,
                "Berry": 32,
                "Stalk": 12,
                "Woody Herb": 8,
                "Pome Fruit": 14
            },
            "supertype_count": {
                "Vegetable": 295,
                "Flower": 28,
                "Herb": 77,
                "Fruit": 144
            },
            "subtype_count": {
                "Sweet Potato": 14,
                "Turmeric": 9,
                "Ginger": 10,
                "Nasturtium": 12,
                "Thyme": 12,
                "Mustard Leaf": 7,
                "Tomato": 34,
                "Fig": 10,
                "Orange": 14,
                "Squash": 13,
                "Cucumber": 3,
                "Almond": 10,
                "Bean": 42,
                "Grapefruit": 7,
                "Cabbage": 14,
                "Onion": 16,
                "Basil": 4,
                "Granadilla": 2,
                "Edible Flower": 3,
                "Plum": 16,
                "Lettuce": 8,
                "Artichoke": 6,
                "Beetroot": 5,
                "Sunflower Seed": 7,
                "Chive": 7,
                "Grape": 16,
                "Naartjie": 4,
                "Blueberry": 7,
                "Lemon Verbena": 12,
                "Pea": 11,
                "Radish": 6,
                "Parsley": 7,
                "Zucchini": 6,
                "Rosemary": 3,
                "Celery": 6,
                "Pepper": 10,
                "Kale": 8,
                "Lemon": 7,
                "Aubergine": 5,
                "Jerusalem Artichoke": 4,
                "Peach": 11,
                "Lime": 1,
                "Gooseberry": 5,
                "Leek": 4,
                "Strawberry": 9,
                "Turnip": 8,
                "Mint": 10,
                "Rhubarb": 6,
                "Curry Leaf": 7,
                "Apple": 14,
                "Chilli": 9,
                "Blackberry": 6,
                "Cauliflower": 5,
                "Coriander": 4,
                "Kei Apple": 5,
                "Pumpkin": 9,
                "Broccoli": 8,
                "Sage": 4,
                "Fennel": 3,
                "Lemon Balm": 7,
                "Marjoram": 3,
                "Sorrel": 4,
                "Oregano": 1,
                "Carrot": 3,
                "Spinach": 1
            }
        },
        {
            "month": 6,
            "year": 2020,
            "type_count": {
                "Cucurbit": 32,
                "Legume": 40,
                "Root": 43,
                "Hard Herb": 23,
                "Nightshade": 67,
                "Berry": 27,
                "Cruciferous": 27,
                "Allium": 26,
                "Citrus": 34,
                "Woody Herb": 16,
                "Stone Fruit": 28,
                "False Fruit": 14,
                "Soft Herb": 21,
                "Nut": 6,
                "Flower": 14,
                "Leaf": 20,
                "Vine Fruit": 18,
                "Pome Fruit": 10,
                "Stalk": 15,
                "Seed": 7
            },
            "supertype_count": {
                "Vegetable": 270,
                "Herb": 60,
                "Fruit": 137,
                "Flower": 21
            },
            "subtype_count": {
                "Pumpkin": 11,
                "Bean": 36,
                "Beetroot": 7,
                "Sage": 6,
                "Tomato": 37,
                "Blueberry": 7,
                "Cauliflower": 4,
                "Leek": 8,
                "Orange": 13,
                "Rosemary": 7,
                "Cabbage": 9,
                "Kei Apple": 2,
                "Onion": 14,
                "Curry Leaf": 7,
                "Strawberry": 8,
                "Plum": 20,
                "Fig": 14,
                "Naartjie": 4,
                "Lemon Balm": 2,
                "Turmeric": 3,
                "Carrot": 5,
                "Chilli": 11,
                "Squash": 12,
                "Pepper": 17,
                "Lemon Verbena": 2,
                "Jerusalem Artichoke": 5,
                "Almond": 6,
                "Sweet Potato": 8,
                "Edible Flower": 4,
                "Grapefruit": 6,
                "Lemon": 3,
                "Spinach": 5,
                "Zucchini": 5,
                "Lime": 8,
                "Fennel": 4,
                "Radish": 5,
                "Grape": 14,
                "Gooseberry": 7,
                "Broccoli": 7,
                "Aubergine": 2,
                "Apple": 10,
                "Coriander": 2,
                "Kale": 7,
                "Ginger": 6,
                "Rhubarb": 10,
                "Peach": 8,
                "Oregano": 9,
                "Granadilla": 4,
                "Blackberry": 3,
                "Sunflower Seed": 7,
                "Cucumber": 4,
                "Marjoram": 6,
                "Artichoke": 7,
                "Sorrel": 3,
                "Pea": 4,
                "Parsley": 4,
                "Mustard Leaf": 9,
                "Turnip": 4,
                "Chive": 4,
                "Celery": 5,
                "Basil": 4,
                "Nasturtium": 3,
                "Mint": 5,
                "Lettuce": 3,
                "Thyme": 2
            }
        },
        {
            "month": 5,
            "year": 2020,
            "type_count": {
                "Stalk": 15,
                "Nightshade": 58,
                "Soft Herb": 35,
                "Leaf": 27,
                "Stone Fruit": 30,
                "Root": 51,
                "Legume": 41,
                "Allium": 35,
                "Vine Fruit": 16,
                "Cruciferous": 34,
                "Berry": 26,
                "Woody Herb": 7,
                "False Fruit": 18,
                "Hard Herb": 16,
                "Flower": 18,
                "Cucurbit": 39,
                "Pome Fruit": 12,
                "Citrus": 33,
                "Seed": 8,
                "Nut": 6
            },
            "supertype_count": {
                "Vegetable": 300,
                "Herb": 58,
                "Fruit": 141,
                "Flower": 26
            },
            "subtype_count": {
                "Rhubarb": 8,
                "Tomato": 33,
                "Parsley": 10,
                "Spinach": 5,
                "Plum": 19,
                "Beetroot": 7,
                "Bean": 37,
                "Onion": 20,
                "Grape": 11,
                "Broccoli": 9,
                "Cabbage": 13,
                "Blackberry": 5,
                "Curry Leaf": 3,
                "Pepper": 7,
                "Fig": 18,
                "Lemon Verbena": 3,
                "Artichoke": 3,
                "Pumpkin": 13,
                "Sweet Potato": 12,
                "Basil": 5,
                "Apple": 12,
                "Lemon Balm": 8,
                "Marjoram": 3,
                "Oregano": 4,
                "Chilli": 11,
                "Peach": 11,
                "Leek": 7,
                "Naartjie": 7,
                "Orange": 11,
                "Lettuce": 11,
                "Grapefruit": 10,
                "Mint": 3,
                "Sunflower Seed": 8,
                "Ginger": 8,
                "Lime": 3,
                "Kei Apple": 3,
                "Coriander": 5,
                "Squash": 13,
                "Thyme": 5,
                "Cauliflower": 5,
                "Radish": 8,
                "Mustard Leaf": 6,
                "Kale": 7,
                "Turnip": 4,
                "Lemon": 2,
                "Blueberry": 9,
                "Nasturtium": 10,
                "Zucchini": 8,
                "Aubergine": 7,
                "Cucumber": 5,
                "Granadilla": 5,
                "Almond": 6,
                "Turmeric": 3,
                "Celery": 7,
                "Chive": 8,
                "Rosemary": 3,
                "Fennel": 4,
                "Edible Flower": 5,
                "Carrot": 7,
                "Sorrel": 5,
                "Pea": 4,
                "Strawberry": 3,
                "Gooseberry": 6,
                "Sage": 2,
                "Jerusalem Artichoke": 2
            }
        },
        {
            "month": 4,
            "year": 2020,
            "type_count": {
                "Flower": 17,
                "Hard Herb": 27,
                "Root": 52,
                "Cucurbit": 34,
                "Leaf": 15,
                "Cruciferous": 34,
                "Legume": 51,
                "Vine Fruit": 22,
                "Soft Herb": 38,
                "Nightshade": 66,
                "Pome Fruit": 13,
                "Woody Herb": 10,
                "Allium": 32,
                "False Fruit": 15,
                "Citrus": 39,
                "Berry": 34,
                "Stone Fruit": 25,
                "Nut": 7,
                "Stalk": 4,
                "Seed": 5
            },
            "supertype_count": {
                "Flower": 22,
                "Herb": 75,
                "Vegetable": 288,
                "Fruit": 155
            },
            "subtype_count": {
                "Edible Flower": 7,
                "Lemon Verbena": 8,
                "Carrot": 5,
                "Squash": 11,
                "Sorrel": 5,
                "Cabbage": 11,
                "Pea": 10,
                "Grape": 19,
                "Lemon Balm": 9,
                "Basil": 7,
                "Tomato": 34,
                "Bean": 41,
                "Apple": 13,
                "Curry Leaf": 9,
                "Parsley": 7,
                "Onion": 18,
                "Fig": 15,
                "Pumpkin": 9,
                "Beetroot": 6,
                "Sweet Potato": 11,
                "Naartjie": 6,
                "Strawberry": 9,
                "Mustard Leaf": 3,
                "Kei Apple": 7,
                "Spinach": 2,
                "Plum": 22,
                "Chive": 8,
                "Fennel": 3,
                "Jerusalem Artichoke": 10,
                "Lemon": 9,
                "Coriander": 5,
                "Granadilla": 3,
                "Blackberry": 6,
                "Leek": 6,
                "Cucumber": 10,
                "Almond": 7,
                "Orange": 8,
                "Radish": 7,
                "Nasturtium": 6,
                "Cauliflower": 6,
                "Lime": 6,
                "Blueberry": 8,
                "Kale": 12,
                "Lettuce": 5,
                "Pepper": 11,
                "Chilli": 14,
                "Zucchini": 4,
                "Sage": 4,
                "Turmeric": 2,
                "Broccoli": 5,
                "Rhubarb": 1,
                "Grapefruit": 10,
                "Marjoram": 7,
                "Mint": 7,
                "Ginger": 7,
                "Aubergine": 7,
                "Sunflower Seed": 5,
                "Celery": 3,
                "Peach": 3,
                "Artichoke": 4,
                "Rosemary": 6,
                "Turnip": 4,
                "Thyme": 2,
                "Gooseberry": 4,
                "Oregano": 1
            }
        },
        {
            "month": 3,
            "year": 2020,
            "type_count": {
                "Seed": 11,
                "Hard Herb": 30,
                "Nightshade": 63,
                "Root": 52,
                "Cruciferous": 39,
                "Citrus": 27,
                "Berry": 29,
                "Pome Fruit": 10,
                "Vine Fruit": 27,
                "Soft Herb": 35,
                "Woody Herb": 15,
                "Flower": 15,
                "False Fruit": 13,
                "Stone Fruit": 35,
                "Legume": 51,
                "Allium": 24,
                "Leaf": 16,
                "Cucurbit": 22,
                "Stalk": 12,
                "Nut": 13
            },
            "supertype_count": {
                "Flower": 26,
                "Herb": 80,
                "Vegetable": 279,
                "Fruit": 154
            },
            "subtype_count": {
                "Sunflower Seed": 11,
                "Lemon Verbena": 10,
                "Tomato": 33,
                "Pepper": 15,
                "Sweet Potato": 10,
                "Turnip": 7,
                "Kale": 12,
                "Naartjie": 5,
                "Turmeric": 7,
                "Blueberry": 5,
                "Apple": 10,
                "Grape": 14,
                "Mint": 6,
                "Coriander": 6,
                "Strawberry": 6,
                "Beetroot": 8,
                "Marjoram": 7,
                "Broccoli": 8,
                "Basil": 7,
                "Carrot": 5,
                "Curry Leaf": 5,
                "Nasturtium": 3,
                "Fig": 13,
                "Grapefruit": 4,
                "Plum": 23,
                "Artichoke": 5,
                "Bean": 43,
                "Jerusalem Artichoke": 4,
                "Leek": 7,
                "Oregano": 10,
                "Orange": 8,
                "Granadilla": 13,
                "Pea": 8,
                "Sorrel": 2,
                "Radish": 7,
                "Zucchini": 1,
                "Celery": 4,
                "Mustard Leaf": 6,
                "Lemon Balm": 6,
                "Aubergine": 6,
                "Almond": 13,
                "Chive": 5,
                "Peach": 12,
                "Onion": 12,
                "Blackberry": 7,
                "Lemon": 5,
                "Sage": 3,
                "Squash": 8,
                "Gooseberry": 6,
                "Ginger": 4,
                "Cabbage": 13,
                "Parsley": 2,
                "Spinach": 4,
                "Kei Apple": 5,
                "Chilli": 9,
                "Pumpkin": 11,
                "Cucumber": 2,
                "Cauliflower": 6,
                "Edible Flower": 7,
                "Thyme": 4,
                "Rhubarb": 8,
                "Lettuce": 4,
                "Rosemary": 6,
                "Fennel": 8,
                "Lime": 5
            }
        },
        {
            "month": 2,
            "year": 2020,
            "type_count": {
                "Root": 48,
                "Allium": 26,
                "Citrus": 32,
                "Soft Herb": 31,
                "Vine Fruit": 30,
                "Nightshade": 57,
                "Flower": 14,
                "Nut": 15,
                "Berry": 21,
                "Stone Fruit": 28,
                "Cruciferous": 41,
                "Legume": 34,
                "Seed": 5,
                "Cucurbit": 26,
                "Hard Herb": 33,
                "Woody Herb": 7,
                "Leaf": 15,
                "Stalk": 10,
                "Pome Fruit": 11,
                "False Fruit": 8
            },
            "supertype_count": {
                "Vegetable": 257,
                "Fruit": 145,
                "Herb": 71,
                "Flower": 19
            },
            "subtype_count": {
                "Jerusalem Artichoke": 9,
                "Onion": 13,
                "Lemon": 7,
                "Coriander": 5,
                "Grape": 21,
                "Pepper": 9,
                "Nasturtium": 6,
                "Chive": 7,
                "Almond": 15,
                "Orange": 14,
                "Leek": 6,
                "Gooseberry": 10,
                "Granadilla": 9,
                "Peach": 11,
                "Aubergine": 5,
                "Naartjie": 6,
                "Kale": 12,
                "Edible Flower": 5,
                "Bean": 28,
                "Sweet Potato": 9,
                "Sunflower Seed": 5,
                "Tomato": 31,
                "Squash": 8,
                "Lime": 4,
                "Ginger": 4,
                "Beetroot": 2,
                "Lemon Verbena": 7,
                "Turmeric": 6,
                "Lemon Balm": 4,
                "Plum": 17,
                "Oregano": 4,
                "Sorrel": 2,
                "Grapefruit": 1,
                "Marjoram": 6,
                "Lettuce": 5,
                "Celery": 5,
                "Apple": 11,
                "Zucchini": 4,
                "Thyme": 7,
                "Cabbage": 13,
                "Broccoli": 10,
                "Blueberry": 3,
                "Fennel": 6,
                "Artichoke": 3,
                "Kei Apple": 4,
                "Mustard Leaf": 5,
                "Pumpkin": 11,
                "Blackberry": 2,
                "Parsley": 6,
                "Fig": 8,
                "Curry Leaf": 3,
                "Sage": 8,
                "Rosemary": 5,
                "Cucumber": 3,
                "Pea": 6,
                "Turnip": 5,
                "Cauliflower": 6,
                "Strawberry": 2,
                "Radish": 6,
                "Chilli": 12,
                "Mint": 4,
                "Basil": 6,
                "Carrot": 7,
                "Spinach": 3,
                "Rhubarb": 5
            }
        },
        {
            "month": 1,
            "year": 2020,
            "type_count": {
                "Hard Herb": 29,
                "Cucurbit": 41,
                "Root": 48,
                "Berry": 36,
                "Nightshade": 72,
                "Citrus": 32,
                "Vine Fruit": 19,
                "Stone Fruit": 32,
                "False Fruit": 16,
                "Legume": 31,
                "Soft Herb": 31,
                "Pome Fruit": 10,
                "Flower": 18,
                "Allium": 26,
                "Cruciferous": 26,
                "Seed": 9,
                "Stalk": 13,
                "Leaf": 20,
                "Woody Herb": 13,
                "Nut": 5
            },
            "supertype_count": {
                "Herb": 73,
                "Vegetable": 277,
                "Fruit": 150,
                "Flower": 27
            },
            "subtype_count": {
                "Lemon Verbena": 6,
                "Zucchini": 11,
                "Sweet Potato": 7,
                "Blackberry": 8,
                "Pumpkin": 14,
                "Chilli": 17,
                "Strawberry": 13,
                "Lemon": 5,
                "Pepper": 13,
                "Marjoram": 8,
                "Grape": 14,
                "Plum": 19,
                "Fig": 16,
                "Kei Apple": 5,
                "Turmeric": 3,
                "Sage": 8,
                "Aubergine": 6,
                "Squash": 12,
                "Bean": 27,
                "Basil": 3,
                "Lemon Balm": 8,
                "Parsley": 5,
                "Pea": 4,
                "Apple": 10,
                "Naartjie": 6,
                "Artichoke": 6,
                "Ginger": 5,
                "Leek": 5,
                "Gooseberry": 5,
                "Cabbage": 6,
                "Kale": 10,
                "Tomato": 36,
                "Sunflower Seed": 9,
                "Rhubarb": 7,
                "Fennel": 7,
                "Peach": 13,
                "Orange": 8,
                "Grapefruit": 8,
                "Rosemary": 3,
                "Blueberry": 5,
                "Spinach": 11,
                "Beetroot": 10,
                "Chive": 5,
                "Nasturtium": 9,
                "Radish": 7,
                "Celery": 6,
                "Carrot": 6,
                "Coriander": 3,
                "Thyme": 4,
                "Onion": 16,
                "Mint": 5,
                "Granadilla": 5,
                "Sorrel": 2,
                "Cauliflower": 5,
                "Mustard Leaf": 4,
                "Curry Leaf": 5,
                "Lime": 5,
                "Lettuce": 3,
                "Turnip": 3,
                "Jerusalem Artichoke": 7,
                "Broccoli": 5,
                "Oregano": 8,
                "Edible Flower": 3,
                "Almond": 5,
                "Cucumber": 4
            }
        }
    ]
]