const dummy_data = [
    {
        "month": 12,
        "year": 2022,
        "type_count": {
            "Soft Herb": 30,
            "Cruciferous": 29,
            "Cucurbit": 28,
            "Root": 45,
            "Nightshade": 66,
            "Hard Herb": 22,
            "Berry": 27,
            "Stone Fruit": 42,
            "Citrus": 24,
            "Flower": 20,
            "Woody Herb": 10,
            "Allium": 31,
            "Pome Fruit": 13,
            "Legume": 43,
            "Vine Fruit": 21,
            "Leaf": 33,
            "Stalk": 9,
            "Nut": 9,
            "Seed": 5,
            "False Fruit": 9
        },
        "supertype_count": {
            "Herb": 62,
            "Vegetable": 284,
            "Fruit": 145,
            "Flower": 25
        },
        "subtype_count": {
            "Basil": 12,
            "Cauliflower": 4,
            "Cucumber": 5,
            "Kale": 14,
            "Carrot": 6,
            "Tomato": 45,
            "Sweet Potato": 10,
            "Mint": 6,
            "Thyme": 6,
            "Pumpkin": 14,
            "Kei Apple": 4,
            "Plum": 28,
            "Lime": 3,
            "Nasturtium": 6,
            "Fennel": 4,
            "Curry Leaf": 5,
            "Leek": 5,
            "Apple": 13,
            "Pea": 7,
            "Bean": 36,
            "Turnip": 6,
            "Peach": 14,
            "Turmeric": 6,
            "Grape": 18,
            "Aubergine": 4,
            "Sage": 5,
            "Mustard Leaf": 8,
            "Orange": 9,
            "Squash": 8,
            "Cabbage": 9,
            "Chilli": 8,
            "Oregano": 5,
            "Rosemary": 5,
            "Onion": 23,
            "Rhubarb": 5,
            "Radish": 4,
            "Spinach": 10,
            "Sorrel": 9,
            "Celery": 4,
            "Pepper": 9,
            "Almond": 9,
            "Edible Flower": 10,
            "Gooseberry": 4,
            "Strawberry": 7,
            "Lemon Verbena": 4,
            "Lemon Balm": 5,
            "Jerusalem Artichoke": 3,
            "Parsley": 3,
            "Grapefruit": 3,
            "Lettuce": 6,
            "Blackberry": 7,
            "Sunflower Seed": 5,
            "Granadilla": 3,
            "Broccoli": 2,
            "Artichoke": 4,
            "Beetroot": 7,
            "Chive": 3,
            "Naartjie": 4,
            "Ginger": 3,
            "Marjoram": 2,
            "Blueberry": 5,
            "Fig": 9,
            "Lemon": 5,
            "Zucchini": 1
        }
    },
    {
        "month": 11,
        "year": 2022,
        "type_count": {
            "Cucurbit": 36,
            "False Fruit": 8,
            "Root": 47,
            "Nightshade": 71,
            "Hard Herb": 26,
            "Citrus": 34,
            "Legume": 36,
            "Stone Fruit": 34,
            "Stalk": 15,
            "Pome Fruit": 18,
            "Vine Fruit": 21,
            "Cruciferous": 33,
            "Berry": 18,
            "Allium": 32,
            "Leaf": 19,
            "Soft Herb": 31,
            "Woody Herb": 9,
            "Flower": 10,
            "Seed": 6,
            "Nut": 4
        },
        "supertype_count": {
            "Vegetable": 289,
            "Fruit": 137,
            "Herb": 66,
            "Flower": 16
        },
        "subtype_count": {
            "Squash": 8,
            "Fig": 8,
            "Pumpkin": 12,
            "Radish": 4,
            "Tomato": 34,
            "Thyme": 5,
            "Lemon": 7,
            "Bean": 32,
            "Carrot": 4,
            "Plum": 24,
            "Sweet Potato": 11,
            "Naartjie": 7,
            "Grapefruit": 5,
            "Rhubarb": 10,
            "Apple": 18,
            "Ginger": 6,
            "Grape": 16,
            "Broccoli": 6,
            "Chilli": 17,
            "Cucumber": 7,
            "Cabbage": 9,
            "Strawberry": 2,
            "Aubergine": 7,
            "Chive": 8,
            "Jerusalem Artichoke": 6,
            "Kei Apple": 5,
            "Marjoram": 8,
            "Sorrel": 6,
            "Orange": 10,
            "Fennel": 5,
            "Zucchini": 9,
            "Coriander": 5,
            "Sage": 4,
            "Oregano": 6,
            "Onion": 18,
            "Kale": 10,
            "Spinach": 6,
            "Lemon Verbena": 7,
            "Parsley": 5,
            "Peach": 10,
            "Pepper": 13,
            "Gooseberry": 5,
            "Lemon Balm": 8,
            "Beetroot": 6,
            "Turmeric": 6,
            "Granadilla": 5,
            "Nasturtium": 5,
            "Artichoke": 3,
            "Cauliflower": 8,
            "Sunflower Seed": 6,
            "Curry Leaf": 3,
            "Mint": 2,
            "Leek": 6,
            "Basil": 6,
            "Turnip": 4,
            "Rosemary": 2,
            "Pea": 4,
            "Mustard Leaf": 5,
            "Blackberry": 4,
            "Lime": 5,
            "Blueberry": 2,
            "Lettuce": 2,
            "Celery": 5,
            "Edible Flower": 2,
            "Almond": 4
        }
    },
    {
        "month": 10,
        "year": 2022,
        "type_count": {
            "Allium": 24,
            "Legume": 40,
            "Nightshade": 68,
            "Soft Herb": 44,
            "Pome Fruit": 11,
            "Stone Fruit": 33,
            "Woody Herb": 6,
            "Citrus": 42,
            "Root": 36,
            "Flower": 17,
            "Vine Fruit": 25,
            "Stalk": 12,
            "Cucurbit": 25,
            "Berry": 27,
            "Hard Herb": 37,
            "Cruciferous": 30,
            "Seed": 7,
            "Leaf": 19,
            "False Fruit": 8,
            "Nut": 10
        },
        "supertype_count": {
            "Vegetable": 254,
            "Herb": 87,
            "Fruit": 156,
            "Flower": 24
        },
        "subtype_count": {
            "Onion": 14,
            "Bean": 32,
            "Chilli": 15,
            "Coriander": 10,
            "Chive": 6,
            "Apple": 11,
            "Peach": 14,
            "Oregano": 3,
            "Tomato": 42,
            "Lime": 10,
            "Lemon": 7,
            "Pea": 8,
            "Aubergine": 4,
            "Plum": 19,
            "Jerusalem Artichoke": 4,
            "Radish": 3,
            "Artichoke": 5,
            "Grape": 19,
            "Celery": 7,
            "Squash": 7,
            "Zucchini": 5,
            "Rhubarb": 5,
            "Blackberry": 6,
            "Marjoram": 7,
            "Turmeric": 6,
            "Mint": 5,
            "Lemon Balm": 4,
            "Strawberry": 6,
            "Kale": 13,
            "Cabbage": 7,
            "Edible Flower": 8,
            "Naartjie": 8,
            "Sweet Potato": 5,
            "Lemon Verbena": 11,
            "Rosemary": 8,
            "Sunflower Seed": 7,
            "Thyme": 9,
            "Lettuce": 5,
            "Spinach": 5,
            "Sorrel": 7,
            "Parsley": 8,
            "Pepper": 7,
            "Basil": 11,
            "Fennel": 6,
            "Grapefruit": 6,
            "Fig": 8,
            "Pumpkin": 9,
            "Granadilla": 6,
            "Orange": 11,
            "Turnip": 5,
            "Ginger": 4,
            "Cucumber": 4,
            "Almond": 10,
            "Kei Apple": 4,
            "Blueberry": 5,
            "Gooseberry": 6,
            "Curry Leaf": 3,
            "Nasturtium": 4,
            "Beetroot": 6,
            "Cauliflower": 5,
            "Leek": 4,
            "Broccoli": 5,
            "Sage": 2,
            "Mustard Leaf": 2,
            "Carrot": 3
        }
    },
    {
        "month": 9,
        "year": 2022,
        "type_count": {
            "Legume": 33,
            "Woody Herb": 11,
            "Cruciferous": 24,
            "Soft Herb": 28,
            "Stone Fruit": 33,
            "Citrus": 36,
            "Berry": 28,
            "Root": 61,
            "Nightshade": 66,
            "Allium": 26,
            "Flower": 14,
            "Leaf": 27,
            "Cucurbit": 30,
            "Hard Herb": 41,
            "False Fruit": 10,
            "Seed": 3,
            "Stalk": 9,
            "Nut": 3,
            "Pome Fruit": 16,
            "Vine Fruit": 13
        },
        "supertype_count": {
            "Vegetable": 276,
            "Herb": 80,
            "Fruit": 139,
            "Flower": 17
        },
        "subtype_count": {
            "Bean": 27,
            "Oregano": 7,
            "Kale": 14,
            "Coriander": 4,
            "Peach": 16,
            "Naartjie": 9,
            "Gooseberry": 7,
            "Ginger": 7,
            "Pepper": 12,
            "Tomato": 37,
            "Cabbage": 7,
            "Sweet Potato": 9,
            "Leek": 6,
            "Nasturtium": 1,
            "Onion": 15,
            "Mustard Leaf": 6,
            "Lemon": 7,
            "Turnip": 9,
            "Squash": 14,
            "Chive": 5,
            "Sage": 8,
            "Lime": 6,
            "Parsley": 6,
            "Orange": 9,
            "Fig": 10,
            "Sunflower Seed": 3,
            "Sorrel": 9,
            "Rosemary": 11,
            "Celery": 5,
            "Marjoram": 10,
            "Jerusalem Artichoke": 5,
            "Beetroot": 8,
            "Fennel": 3,
            "Turmeric": 9,
            "Almond": 3,
            "Curry Leaf": 4,
            "Blueberry": 9,
            "Strawberry": 6,
            "Grapefruit": 5,
            "Pea": 6,
            "Lettuce": 7,
            "Artichoke": 5,
            "Mint": 7,
            "Plum": 17,
            "Thyme": 5,
            "Zucchini": 6,
            "Radish": 6,
            "Apple": 16,
            "Chilli": 6,
            "Lemon Balm": 5,
            "Rhubarb": 4,
            "Aubergine": 11,
            "Edible Flower": 8,
            "Pumpkin": 7,
            "Grape": 10,
            "Kei Apple": 1,
            "Basil": 3,
            "Blackberry": 5,
            "Granadilla": 3,
            "Carrot": 8,
            "Lemon Verbena": 7,
            "Spinach": 5,
            "Broccoli": 2,
            "Cucumber": 3,
            "Cauliflower": 1
        }
    },
    {
        "month": 8,
        "year": 2022,
        "type_count": {
            "Allium": 28,
            "False Fruit": 9,
            "Cruciferous": 29,
            "Soft Herb": 25,
            "Pome Fruit": 13,
            "Root": 43,
            "Stone Fruit": 24,
            "Cucurbit": 33,
            "Leaf": 23,
            "Nightshade": 58,
            "Stalk": 11,
            "Hard Herb": 24,
            "Berry": 28,
            "Woody Herb": 10,
            "Citrus": 37,
            "Flower": 19,
            "Legume": 38,
            "Vine Fruit": 21,
            "Seed": 2,
            "Nut": 2
        },
        "supertype_count": {
            "Vegetable": 263,
            "Fruit": 134,
            "Herb": 59,
            "Flower": 21
        },
        "subtype_count": {
            "Onion": 16,
            "Fig": 9,
            "Kale": 9,
            "Lemon Balm": 2,
            "Apple": 13,
            "Jerusalem Artichoke": 11,
            "Plum": 15,
            "Parsley": 4,
            "Zucchini": 9,
            "Spinach": 7,
            "Aubergine": 7,
            "Cauliflower": 4,
            "Rhubarb": 7,
            "Rosemary": 8,
            "Strawberry": 5,
            "Peach": 9,
            "Oregano": 4,
            "Basil": 5,
            "Grapefruit": 9,
            "Lettuce": 7,
            "Gooseberry": 7,
            "Broccoli": 5,
            "Artichoke": 7,
            "Tomato": 33,
            "Orange": 16,
            "Sage": 4,
            "Curry Leaf": 6,
            "Bean": 33,
            "Celery": 4,
            "Blackberry": 6,
            "Ginger": 2,
            "Pumpkin": 16,
            "Nasturtium": 8,
            "Pepper": 13,
            "Sweet Potato": 14,
            "Kei Apple": 8,
            "Granadilla": 6,
            "Beetroot": 5,
            "Coriander": 8,
            "Marjoram": 5,
            "Grape": 15,
            "Cabbage": 11,
            "Cucumber": 3,
            "Lemon Verbena": 5,
            "Squash": 5,
            "Edible Flower": 4,
            "Lemon": 3,
            "Sunflower Seed": 2,
            "Lime": 4,
            "Chive": 3,
            "Fennel": 4,
            "Mustard Leaf": 3,
            "Blueberry": 2,
            "Thyme": 2,
            "Sorrel": 6,
            "Pea": 5,
            "Leek": 9,
            "Chilli": 5,
            "Mint": 2,
            "Naartjie": 5,
            "Carrot": 2,
            "Radish": 7,
            "Turnip": 2,
            "Almond": 2
        }
    },
    {
        "month": 7,
        "year": 2022,
        "type_count": {
            "Nightshade": 63,
            "Berry": 40,
            "Allium": 25,
            "Stone Fruit": 25,
            "Vine Fruit": 24,
            "Stalk": 10,
            "Cruciferous": 37,
            "Legume": 53,
            "Hard Herb": 22,
            "Soft Herb": 25,
            "Cucurbit": 35,
            "False Fruit": 15,
            "Root": 46,
            "Seed": 7,
            "Citrus": 21,
            "Flower": 15,
            "Pome Fruit": 9,
            "Leaf": 25,
            "Nut": 2,
            "Woody Herb": 10
        },
        "supertype_count": {
            "Vegetable": 294,
            "Fruit": 136,
            "Herb": 57,
            "Flower": 22
        },
        "subtype_count": {
            "Chilli": 18,
            "Blueberry": 8,
            "Leek": 9,
            "Peach": 11,
            "Granadilla": 4,
            "Celery": 5,
            "Grape": 20,
            "Kale": 13,
            "Pea": 7,
            "Chive": 6,
            "Sage": 2,
            "Tomato": 29,
            "Bean": 46,
            "Parsley": 5,
            "Lemon Balm": 7,
            "Squash": 9,
            "Fig": 15,
            "Zucchini": 8,
            "Turnip": 6,
            "Strawberry": 9,
            "Sunflower Seed": 7,
            "Fennel": 5,
            "Carrot": 4,
            "Basil": 2,
            "Blackberry": 8,
            "Ginger": 4,
            "Thyme": 4,
            "Orange": 7,
            "Edible Flower": 9,
            "Cucumber": 6,
            "Broccoli": 6,
            "Beetroot": 6,
            "Apple": 9,
            "Pumpkin": 12,
            "Cabbage": 11,
            "Lemon Verbena": 4,
            "Coriander": 3,
            "Plum": 14,
            "Rosemary": 11,
            "Onion": 10,
            "Nasturtium": 4,
            "Pepper": 10,
            "Mustard Leaf": 6,
            "Spinach": 9,
            "Turmeric": 9,
            "Rhubarb": 5,
            "Jerusalem Artichoke": 5,
            "Sweet Potato": 9,
            "Aubergine": 6,
            "Sorrel": 5,
            "Almond": 2,
            "Kei Apple": 8,
            "Gooseberry": 7,
            "Cauliflower": 7,
            "Oregano": 6,
            "Naartjie": 5,
            "Lime": 4,
            "Lemon": 3,
            "Curry Leaf": 4,
            "Radish": 3,
            "Mint": 3,
            "Artichoke": 2,
            "Grapefruit": 2,
            "Lettuce": 5,
            "Marjoram": 1
        }
    },
    {
        "month": 6,
        "year": 2022,
        "type_count": {
            "Legume": 45,
            "Leaf": 23,
            "Nut": 2,
            "Cruciferous": 32,
            "Root": 48,
            "Cucurbit": 37,
            "Soft Herb": 31,
            "Vine Fruit": 17,
            "Citrus": 37,
            "Flower": 21,
            "Hard Herb": 30,
            "Berry": 28,
            "Stone Fruit": 42,
            "Allium": 31,
            "Nightshade": 49,
            "Woody Herb": 7,
            "False Fruit": 12,
            "Seed": 7,
            "Pome Fruit": 7,
            "Stalk": 10
        },
        "supertype_count": {
            "Vegetable": 275,
            "Fruit": 145,
            "Herb": 68,
            "Flower": 28
        },
        "subtype_count": {
            "Bean": 41,
            "Spinach": 6,
            "Almond": 2,
            "Kale": 12,
            "Beetroot": 7,
            "Pumpkin": 12,
            "Parsley": 8,
            "Grape": 10,
            "Grapefruit": 6,
            "Artichoke": 4,
            "Sage": 7,
            "Strawberry": 7,
            "Peach": 20,
            "Granadilla": 7,
            "Orange": 11,
            "Sweet Potato": 16,
            "Plum": 22,
            "Cabbage": 8,
            "Turnip": 6,
            "Onion": 23,
            "Tomato": 26,
            "Chilli": 15,
            "Blackberry": 5,
            "Marjoram": 5,
            "Turmeric": 4,
            "Curry Leaf": 3,
            "Blueberry": 4,
            "Nasturtium": 8,
            "Fig": 12,
            "Broccoli": 10,
            "Sunflower Seed": 7,
            "Cauliflower": 2,
            "Squash": 12,
            "Edible Flower": 9,
            "Sorrel": 7,
            "Apple": 7,
            "Oregano": 4,
            "Leek": 5,
            "Mint": 3,
            "Lemon": 4,
            "Lime": 7,
            "Rhubarb": 5,
            "Mustard Leaf": 8,
            "Rosemary": 7,
            "Jerusalem Artichoke": 3,
            "Aubergine": 4,
            "Lemon Verbena": 9,
            "Kei Apple": 6,
            "Celery": 5,
            "Cucumber": 8,
            "Carrot": 4,
            "Lemon Balm": 6,
            "Lettuce": 2,
            "Radish": 6,
            "Zucchini": 5,
            "Ginger": 2,
            "Gooseberry": 6,
            "Basil": 4,
            "Fennel": 7,
            "Pepper": 4,
            "Chive": 3,
            "Pea": 4,
            "Coriander": 3,
            "Naartjie": 9,
            "Thyme": 2
        }
    },
    {
        "month": 5,
        "year": 2022,
        "type_count": {
            "Allium": 27,
            "Root": 50,
            "Flower": 15,
            "Legume": 55,
            "Nightshade": 71,
            "Woody Herb": 13,
            "Stone Fruit": 47,
            "Soft Herb": 32,
            "Pome Fruit": 10,
            "Leaf": 22,
            "Citrus": 35,
            "Berry": 28,
            "False Fruit": 12,
            "Hard Herb": 33,
            "Cruciferous": 42,
            "Cucurbit": 32,
            "Vine Fruit": 18,
            "Stalk": 18,
            "Nut": 6,
            "Seed": 2
        },
        "supertype_count": {
            "Vegetable": 317,
            "Flower": 17,
            "Herb": 78,
            "Fruit": 156
        },
        "subtype_count": {
            "Onion": 16,
            "Ginger": 3,
            "Artichoke": 5,
            "Bean": 46,
            "Chilli": 15,
            "Curry Leaf": 6,
            "Beetroot": 8,
            "Tomato": 37,
            "Plum": 35,
            "Aubergine": 8,
            "Fennel": 6,
            "Apple": 10,
            "Lettuce": 3,
            "Peach": 12,
            "Oregano": 7,
            "Orange": 12,
            "Radish": 7,
            "Naartjie": 6,
            "Blueberry": 8,
            "Fig": 12,
            "Mustard Leaf": 8,
            "Chive": 10,
            "Rosemary": 6,
            "Cauliflower": 10,
            "Pumpkin": 10,
            "Grape": 10,
            "Squash": 12,
            "Lime": 5,
            "Jerusalem Artichoke": 7,
            "Parsley": 4,
            "Rhubarb": 9,
            "Pea": 9,
            "Kale": 18,
            "Almond": 6,
            "Celery": 9,
            "Zucchini": 6,
            "Marjoram": 6,
            "Carrot": 3,
            "Mint": 7,
            "Blackberry": 7,
            "Grapefruit": 5,
            "Cabbage": 9,
            "Lemon Verbena": 7,
            "Sweet Potato": 14,
            "Sage": 10,
            "Pepper": 11,
            "Granadilla": 8,
            "Sorrel": 5,
            "Turmeric": 2,
            "Coriander": 8,
            "Edible Flower": 4,
            "Turnip": 6,
            "Lemon": 7,
            "Spinach": 6,
            "Strawberry": 3,
            "Nasturtium": 6,
            "Kei Apple": 2,
            "Broccoli": 5,
            "Thyme": 4,
            "Gooseberry": 8,
            "Lemon Balm": 3,
            "Cucumber": 4,
            "Basil": 4,
            "Sunflower Seed": 2,
            "Leek": 1
        }
    },
    {
        "month": 4,
        "year": 2022,
        "type_count": {
            "Nightshade": 66,
            "Soft Herb": 40,
            "Pome Fruit": 10,
            "Cucurbit": 34,
            "Citrus": 31,
            "Vine Fruit": 11,
            "Leaf": 15,
            "Berry": 31,
            "Woody Herb": 12,
            "Stone Fruit": 28,
            "Root": 53,
            "Cruciferous": 37,
            "Allium": 23,
            "Legume": 43,
            "Flower": 14,
            "Hard Herb": 21,
            "Seed": 3,
            "Nut": 5,
            "Stalk": 19,
            "False Fruit": 8
        },
        "supertype_count": {
            "Vegetable": 290,
            "Herb": 73,
            "Fruit": 124,
            "Flower": 17
        },
        "subtype_count": {
            "Chilli": 12,
            "Coriander": 8,
            "Apple": 10,
            "Pumpkin": 15,
            "Squash": 11,
            "Orange": 13,
            "Grape": 11,
            "Lettuce": 3,
            "Mint": 7,
            "Parsley": 8,
            "Strawberry": 8,
            "Oregano": 6,
            "Peach": 7,
            "Radish": 10,
            "Kale": 8,
            "Blueberry": 5,
            "Onion": 14,
            "Curry Leaf": 6,
            "Bean": 39,
            "Edible Flower": 7,
            "Plum": 21,
            "Blackberry": 5,
            "Beetroot": 6,
            "Kei Apple": 8,
            "Thyme": 6,
            "Tomato": 36,
            "Basil": 5,
            "Turmeric": 5,
            "Sunflower Seed": 3,
            "Lemon": 4,
            "Ginger": 7,
            "Almond": 5,
            "Pepper": 15,
            "Rosemary": 6,
            "Fennel": 9,
            "Cabbage": 13,
            "Carrot": 10,
            "Jerusalem Artichoke": 2,
            "Celery": 10,
            "Gooseberry": 5,
            "Leek": 1,
            "Lemon Verbena": 4,
            "Sorrel": 6,
            "Cucumber": 2,
            "Artichoke": 5,
            "Lemon Balm": 3,
            "Naartjie": 5,
            "Cauliflower": 8,
            "Fig": 8,
            "Zucchini": 6,
            "Sage": 3,
            "Nasturtium": 2,
            "Grapefruit": 3,
            "Chive": 8,
            "Lime": 6,
            "Rhubarb": 9,
            "Broccoli": 8,
            "Sweet Potato": 11,
            "Pea": 4,
            "Mustard Leaf": 4,
            "Aubergine": 3,
            "Marjoram": 2,
            "Spinach": 2,
            "Turnip": 2
        }
    },
    {
        "month": 3,
        "year": 2022,
        "type_count": {
            "Stone Fruit": 33,
            "Allium": 27,
            "False Fruit": 14,
            "Nightshade": 58,
            "Nut": 7,
            "Citrus": 37,
            "Root": 52,
            "Cruciferous": 34,
            "Soft Herb": 24,
            "Stalk": 11,
            "Hard Herb": 26,
            "Leaf": 26,
            "Legume": 39,
            "Cucurbit": 31,
            "Vine Fruit": 24,
            "Pome Fruit": 11,
            "Seed": 8,
            "Berry": 26,
            "Woody Herb": 7,
            "Flower": 16
        },
        "supertype_count": {
            "Fruit": 152,
            "Vegetable": 278,
            "Herb": 57,
            "Flower": 24
        },
        "subtype_count": {
            "Plum": 26,
            "Onion": 17,
            "Fig": 14,
            "Tomato": 35,
            "Almond": 7,
            "Grapefruit": 6,
            "Ginger": 7,
            "Cauliflower": 7,
            "Sweet Potato": 9,
            "Parsley": 2,
            "Rhubarb": 5,
            "Rosemary": 6,
            "Mustard Leaf": 5,
            "Bean": 33,
            "Chilli": 9,
            "Pepper": 10,
            "Celery": 6,
            "Squash": 18,
            "Kale": 11,
            "Zucchini": 5,
            "Grape": 17,
            "Apple": 11,
            "Sunflower Seed": 8,
            "Granadilla": 7,
            "Lemon": 4,
            "Radish": 5,
            "Broccoli": 5,
            "Turnip": 4,
            "Jerusalem Artichoke": 7,
            "Lettuce": 9,
            "Carrot": 10,
            "Orange": 11,
            "Lime": 11,
            "Sorrel": 3,
            "Blueberry": 8,
            "Turmeric": 5,
            "Fennel": 5,
            "Oregano": 4,
            "Edible Flower": 11,
            "Mint": 3,
            "Strawberry": 4,
            "Sage": 7,
            "Curry Leaf": 3,
            "Lemon Verbena": 6,
            "Basil": 4,
            "Kei Apple": 7,
            "Leek": 5,
            "Naartjie": 5,
            "Pumpkin": 3,
            "Spinach": 9,
            "Chive": 5,
            "Coriander": 5,
            "Artichoke": 1,
            "Cabbage": 11,
            "Blackberry": 3,
            "Pea": 6,
            "Peach": 7,
            "Gooseberry": 4,
            "Thyme": 3,
            "Lemon Balm": 5,
            "Marjoram": 4,
            "Beetroot": 5,
            "Nasturtium": 4,
            "Aubergine": 4,
            "Cucumber": 5
        }
    },
    {
        "month": 2,
        "year": 2022,
        "type_count": {
            "Root": 55,
            "Stone Fruit": 35,
            "Nightshade": 65,
            "Hard Herb": 32,
            "Stalk": 12,
            "Pome Fruit": 7,
            "Legume": 56,
            "Cucurbit": 29,
            "Soft Herb": 22,
            "Citrus": 31,
            "Vine Fruit": 23,
            "Flower": 17,
            "Cruciferous": 30,
            "Allium": 26,
            "False Fruit": 15,
            "Berry": 19,
            "Leaf": 27,
            "Woody Herb": 14,
            "Seed": 12,
            "Nut": 11
        },
        "supertype_count": {
            "Vegetable": 300,
            "Fruit": 141,
            "Herb": 68,
            "Flower": 29
        },
        "subtype_count": {
            "Beetroot": 6,
            "Plum": 23,
            "Pepper": 9,
            "Sage": 9,
            "Celery": 8,
            "Apple": 7,
            "Bean": 52,
            "Turmeric": 6,
            "Tomato": 37,
            "Pumpkin": 11,
            "Mint": 5,
            "Pea": 4,
            "Grapefruit": 3,
            "Thyme": 5,
            "Orange": 14,
            "Radish": 4,
            "Lime": 7,
            "Granadilla": 4,
            "Cucumber": 6,
            "Grape": 19,
            "Edible Flower": 3,
            "Cabbage": 17,
            "Onion": 16,
            "Fig": 15,
            "Strawberry": 3,
            "Jerusalem Artichoke": 10,
            "Mustard Leaf": 9,
            "Gooseberry": 3,
            "Marjoram": 5,
            "Blackberry": 4,
            "Chilli": 15,
            "Curry Leaf": 7,
            "Lettuce": 6,
            "Parsley": 2,
            "Rosemary": 4,
            "Squash": 5,
            "Blueberry": 7,
            "Artichoke": 7,
            "Oregano": 7,
            "Carrot": 8,
            "Lemon Verbena": 9,
            "Sunflower Seed": 12,
            "Rhubarb": 4,
            "Zucchini": 7,
            "Almond": 11,
            "Turnip": 6,
            "Kale": 5,
            "Coriander": 2,
            "Sweet Potato": 8,
            "Ginger": 7,
            "Lemon Balm": 7,
            "Chive": 5,
            "Peach": 12,
            "Naartjie": 4,
            "Nasturtium": 7,
            "Sorrel": 7,
            "Fennel": 1,
            "Cauliflower": 3,
            "Broccoli": 5,
            "Basil": 5,
            "Aubergine": 4,
            "Leek": 5,
            "Lemon": 3,
            "Kei Apple": 2,
            "Spinach": 5
        }
    },
    {
        "month": 1,
        "year": 2022,
        "type_count": {
            "Flower": 19,
            "Leaf": 20,
            "Soft Herb": 32,
            "False Fruit": 16,
            "Cucurbit": 37,
            "Legume": 48,
            "Nightshade": 68,
            "Cruciferous": 40,
            "Stone Fruit": 39,
            "Hard Herb": 34,
            "Allium": 26,
            "Root": 46,
            "Stalk": 10,
            "Berry": 17,
            "Woody Herb": 9,
            "Citrus": 31,
            "Seed": 9,
            "Vine Fruit": 13,
            "Pome Fruit": 13,
            "Nut": 6
        },
        "supertype_count": {
            "Flower": 28,
            "Vegetable": 295,
            "Herb": 75,
            "Fruit": 135
        },
        "subtype_count": {
            "Artichoke": 6,
            "Spinach": 6,
            "Mint": 6,
            "Fig": 16,
            "Cucumber": 5,
            "Bean": 45,
            "Tomato": 30,
            "Kale": 13,
            "Plum": 23,
            "Rosemary": 11,
            "Thyme": 5,
            "Onion": 15,
            "Mustard Leaf": 7,
            "Basil": 3,
            "Sorrel": 4,
            "Aubergine": 4,
            "Lemon Verbena": 6,
            "Squash": 11,
            "Sweet Potato": 9,
            "Pepper": 12,
            "Celery": 6,
            "Chilli": 22,
            "Edible Flower": 6,
            "Strawberry": 3,
            "Cabbage": 18,
            "Marjoram": 7,
            "Radish": 8,
            "Pumpkin": 16,
            "Broccoli": 5,
            "Beetroot": 2,
            "Curry Leaf": 4,
            "Blackberry": 3,
            "Naartjie": 5,
            "Sunflower Seed": 9,
            "Fennel": 8,
            "Nasturtium": 7,
            "Orange": 9,
            "Grape": 10,
            "Turmeric": 5,
            "Lime": 7,
            "Zucchini": 5,
            "Pea": 3,
            "Jerusalem Artichoke": 5,
            "Oregano": 5,
            "Peach": 16,
            "Parsley": 6,
            "Kei Apple": 4,
            "Cauliflower": 4,
            "Rhubarb": 4,
            "Apple": 13,
            "Gooseberry": 2,
            "Lemon Balm": 6,
            "Leek": 6,
            "Lemon": 5,
            "Sage": 5,
            "Granadilla": 3,
            "Turnip": 6,
            "Blueberry": 5,
            "Chive": 5,
            "Carrot": 4,
            "Almond": 6,
            "Ginger": 7,
            "Grapefruit": 5,
            "Lettuce": 3,
            "Coriander": 3
        }
    }
]

export default dummy_data;