const subtypes_pie = [
    { "Almond": 0 },
    { "Apple": 0 },
    { "Artichoke": 0 },
    { "Aubergine": 0 },
    { "Basil": 0 },
    { "Bean": 0 },
    { "Beetroot": 0 },
    { "Blackberry": 0 },
    { "Blueberry": 0 },
    { "Broccoli": 0 },
    { "Squash": 0 },
    { "Cabbage": 0 },
    { "Carrot": 0 },
    { "Cauliflower": 0 },
    { "Kale": 0 },
    { "Celery": 0 },
    { "Chilli": 0 },
    { "Chive": 0 },
    { "Coriander": 0 },
    { "Cucumber": 0 },
    { "Curry Leaf": 0 },
    { "Edible Flower": 0 },
    { "Fennel": 0 },
    { "Fig": 0 },
    { "Ginger": 0 },
    { "Gooseberry": 0 },
    { "Granadilla": 0 },
    { "Grape": 0 },
    { "Grapefruit": 0 },
    { "Jerusalem Artichoke": 0 },
    { "Kei Apple": 0 },
    { "Leek": 0 },
    { "Lemon": 0 },
    { "Lemon Balm": 0 },
    { "Lemon Verbena": 0 },
    { "Lettuce": 0 },
    { "Lime": 0 },
    { "Marjoram": 0 },
    { "Mint": 0 },
    { "Mustard Leaf": 0 },
    { "Naartjie": 0 },
    { "Nasturtium": 0 },
    { "Onion": 0 },
    { "Orange": 0 },
    { "Oregano": 0 },
    { "Parsley": 0 },
    { "Pea": 0 },
    { "Peach": 0 },
    { "Pepper": 0 },
    { "Plum": 0 },
    { "Pumpkin": 0 },
    { "Radish": 0 },
    { "Rhubarb": 0 },
    { "Rosemary": 0 },
    { "Sage": 0 },
    { "Sorrel": 0 },
    { "Spinach": 0 },
    { "Strawberry": 0 },
    { "Sunflower Seed": 0 },
    { "Sweet Potato": 0 },
    { "Thyme": 0 },
    { "Tomato": 0 },
    { "Turmeric": 0 },
    { "Turnip": 0 },
    { "Zucchini": 0 },
]

export default subtypes_pie;