name: Codecov CI

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Codecov

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests and collect coverage
        run: npm test -- --coverage --watchAll | echo "q"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}