name: Codecov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install --force
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll --testPathPattern='__tests__/*.{test,spec}.js|__tests__/hello.test.js'


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests, hellotest
          directory: ./coverage