name:  farmers-guild

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
                - uses: actions/checkout@master
                - uses: codecov/codecov-action@v3
                  with:
                    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
                    files: ./coverage1.xml,./coverage2.xml # optional
                    flags: unittests # optional
                    name: codecov-umbrella # optional
                    fail_ci_if_error: true # optional (default = false)
                    verbose: true # optional (default = false)