name: Codecov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll --testPathPattern=__tests__/*.{test,spec}.js __tests__/random.test.js | echo "q"


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests, randomtests
          directory: ./coverage
